[tool.black]
line-length = 120
target-version = ['py37']

[tool.isort]
line_length = 120
skip = "__init__.py"
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
multi_line_output = 3
length_sort_stdlib = 1

